name: Django CI

on:
  push:
    branches: [ "main", "github-pipeline" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        apt-get install -y build-essential python3-pip 
        python -m pip install --upgrade pip sqlite-utils
        cp github.env .env
        make github-install
    - name: Run Tests
      run: |
        make test
