version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A waltzing_matilda_trading worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A waltzing_matilda_trading beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: waltzing_matilda_trading
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
